import { SearchResult, MenuOption, MenuPosition, CloseType, ShareType, PosterDetail } from '../../interface/bridge';
export declare function openSearch(type: string, hint: string, message: string): SearchResult;
export declare function toggleSearch(isHide: boolean): void;
export declare function SetH5Header(n: string): void;
export declare function leftMenu(n: MenuOption): void;
export declare function toggleMenu(n: MenuPosition, show: boolean): void;
export declare function rightMenu(n: MenuOption): void;
export declare function articleDetail(url: string, title: string, btnTxt: string): Promise<string>;
export declare function viewPdf(url: string, title: string, btnTxt: string): Promise<string>;
export declare function startAudioRec(isShow: boolean): Promise<string>;
export declare function callCamera(): Promise<string>;
export declare function tailorCamera(n: number, bool: boolean, width: number, height: number): Promise<string>;
export declare function callAddress(): Promise<string>;
export declare function idCardScan(): Promise<string>;
export declare function saveImage(base64String: string): void;
export declare function getBank(): Promise<string>;
export declare function caSign(name: string, type: string, keyWord: string): Promise<string>;
export declare function getJob(): Promise<string>;
export declare function getCustomer(): Promise<string>;
export declare function closeWebview(n: CloseType): void;
export declare function takeUserImageMultiple(count: number): Promise<Array<string>>;
export declare function callCameraMultiple(count: number): Promise<Array<string>>;
export declare function shareShare(type: ShareType, url: string, imageUrl: string, title: string, desc: string, callback: string): Promise<string>;
export declare function wechatShare(webPageUrl: string, path: string, imageUrl: string, title: string, desc: string, callback: string): void;
export declare function showShareBtn(type: ShareType, url: string, imageUrl: string, title: string, desc: string, callback: string): void;
export declare function showShareArr(javascript: string, url: string, imageUrl: string, title: string, desc: string): void;
export declare function showRiskArr(baseImg: string, fun1: string, baseImg2: string, fun2: string): void;
export declare function nativeAjax(url: string, data: any, method: string): void;
export declare function showPosterDetail(param: Array<PosterDetail>, index: number): void;
export declare function sendSms(telNum: string, content: string): void;
export declare function shareShareEntry(type: ShareType, url: string, title: string, desc: string, callback: string): void;
export declare function goBack(pathName: string): void;
